### ISSUE TITLE
Crash: java.lang.RuntimeException

### ISSUE THREAD

**Issue by Lordbaane** [CamoMano/Vanilla-Enhanced#15]
During play, turned and spotted an Enderman and the game suddenly stalled then crashed:

---- Minecraft Crash Report ----
// You're mean.

Time: 09/10/20 9:44 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'vanillaenhanced'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/biome/v1/OverworldClimate
	at com.vanillaenhanced.biome.Biomes.init(Biomes.java:62)
	at com.vanillaenhanced.VanillaEnhanced.onInitialize(VanillaEnhanced.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 19 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.biome.v1.OverworldClimate
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:166)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2699257944 bytes (2574 MB) / 5052039168 bytes (4818 MB) up to 7529299968 bytes (7180 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx8077m
	Fabric Mods: 
		adabraniummod: Adabranium Mod 1.2.1
		adapaxels: AdaPaxels 1.0.3
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.2
		bettercaves: YUNG's Better Caves 1.16.2-1.0.2
		blue_endless_jankson: jankson +
		byg: BYG 1.0.13
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		cardinal-components-item: Cardinal Components API (items) 2.6.0
		carrier: Carrier 1.3.0
		carvepump: Carve My Pumpkin 1.0.2
		cavebiomes: Cave Biomes 0.4.0
		chainmail: Chainmail 0.5.0
		cleanview: CleanView 1.16.3-v1-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.1
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		curios: Curios API 0.0.8-1.16.3
		dawn: Dawn API 1.2
		durabilityviewer: Giselbaers Durability Viewer 1.16.2-fabric0.17.2-1.8.7
		economical_villager_trading: Economical Villager Trading 1.0.1-1+1.16.1-1.16.3
		elytra-recipe: Elytra Recipe 1.0.1
		expandedstorage: ExpandedStorage 5.6.30
		fabric: Fabric API 0.20.2+build.402-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad95
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd195
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd695
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d695
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5fa7
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea18895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa195
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced895
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced895
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de695
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d95
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e95
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049095
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea18895
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e95
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e95
		fabricloader: Fabric Loader 0.10.1+build.209
		falling_tree: FallingTree 2.4.0
		fiber: fiber 0.23.0-2
		flyring: Ring of Flight 0.1.0+1.16.3
		gbfabrictools: GBfabrictools 1.2.3+1.16.2
		gottaclimbfast: Gotta Climb Fast! 1.0
		gravel-ores: Gravel Ores 1.2.0+1.16.2
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		imm_ptl_core: Immersive Portals Core 0.34
		immersive_portals: Immersive Portals 0.34
		inventorypause: Inventory Pause 1.0.3
		inventorysorter: Inventory Sorter 1.7.4-1.16
		jankson: Jankson 3.0.0+j1.2.0
		kyrptconfig: Kytpt Config 1.1.2-1.16
		lambdabettergrass: LambdaBetterGrass 1.0.1+1.16.3
		libcd: LibCapableData 3.0.2+1.16.2
		malilib: MaLiLib 0.10.0-dev.21+arne.1
		materialisation: Materialisation 3.0.3
		medievalweapons: Medieval Weapons 1.0.0
		minecraft: Minecraft 1.16.3
		mo_glass: Mo Glass 1.4-MC1.16.3
		modmenu: Mod Menu 1.14.6+build.31
		moenchantments: Mo'Enchantments 1.13.7
		more_gems: More Gems 1.1.3
		morebookshelves: Bookshelving 0.0.0
		mostructures: Mo' Structures 1.0.0-pre3+mc.1.16.2
		moundertweaks: MounderTweaks 1.4.0
		nbtcrafting: NBT Crafting 2.0.0-rc.7+mc1.16.2-pre1
		nookbuild: NookBuild 1.1
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		overpowered_mending: Overpowered Mending 2.2.2
		packed: Packed Storage 1.0.8
		playerabilitylib: Pal 1.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.4.2+build.73
		repurposed_structures: Repurposed Structures 1.16.3-1.6.4
		ring_of_attraction: Ring Of Attraction 1.0.23
		ring_of_growth: Ring Of Growth 1.0.21
		ringsofascension: Rings of Ascension 1.0.7
		rotten: FleshZ 1.2.2
		roughlyenoughitems: Roughly Enough Items 5.6.1
		roughlyenoughitems-api: REI (API) 5.6.1
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.6.1
		roughlyenoughitems-runtime: REI (Runtime) 5.6.1
		rpgstats: RPGStats 2.3.2+1.16.3
		shieldisruptor: Shield Disruptor 1.1.1
		silkspawners: SilkSpawners 1.0.0
		simple_backpack: SimpleBackpack 1.0.28
		spruceui: SpruceUI 1.6.4
		survivalisland: Survival Island 0.1.5
		team_reborn_energy: Energy 0.1.0
		tinytweaks: TinyTweaks 1.0.13
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		tool_action_helper: Tool Action Helper 1.0.1
		torohealth: ToroHealth Damage Indicators 1.16.3-fabric-1
		trinkets: Trinkets 2.6.4
		tweakeroo: Tweakeroo 0.10.0-dev.20200913.175041
		vanillaenhanced: VanillaEnhanced 1.3.0
		voyager: Voyager 1.0.0
		xaerominimap: Xaero's Minimap 20.25.0
		xaeroworldmap: Xaero's World Map 1.11.0
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Lordbaane** [comment]
Version: 1.3.0

**Comment by CamoMano** [comment]
It looks like you are using an older version of the Fabric API which doesn't include the Biome API. Try using a newer version. https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by Lordbaane** [comment]
I'll check and close for now.

**Comment by CamoMano** [comment]
Any luck?

**Comment by Lordbaane** [comment]
Seems to be stable now.
